name: Cache CI

on:
  workflow_dispatch:
  push:

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: cache-c525b55

      - name: prime-cache-c525b55
        run: |
          if [ "${{ steps.cache-step.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit"
          else
            echo "Cache miss"
          fi
